config/routes.rb
Rails.application.routes.draw do
  resources :buses, only: :show

  get 'site/location'
  get 'site/nearby_buses'
  get 'site/index'
  get 'site/reload_station'
  get 'site/search'

  resources :stations, only: ["show"]

  root 'site#index'

end

app/models/bus.rb
class Bus < ActiveRecord::Base
  validates :number, uniqueness: true
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :bus_code_id, :code, uniqueness: true
  geocoded_by :code
  reverse_geocoded_by :latitude, :longitude

  def buses
    Bus.where("? = ANY (routes_ids)", self.code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :find_bus, only: :show

  def show
    @bus_routes = BusDecorator.new(@bus).routes_left_from(params[:station_code])
  end

  private
  def find_bus
    @bus = Bus.find_by(number: params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @stations = Station.order(id: 'asc').page(params[:page]).per(10)
  end

  def location
  end

  def search
    q = BusAndStationQuery.find(params[:search])
    return redirect_to station_path(q.id) if q.is_a? Station
    return redirect_to bus_path(q.id) if q.is_a? Bus
    raise ActionController::RoutingError.new('Not Found')
  end

  def nearby_buses
    @stations = Location.nearby_buses1(params[:lat], params[:long])
  end

  def reload_station
    station = Station.find_by(code: params[:station])
    @buses = station.buses
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :find_station

  def show
    @station = StationDecorator.new(@station)
  end

  private
  def find_station
    @station = Station.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def color_code(time)
    return if time.nil?
    if time >= 10
      "alert"
    elsif (5..9).include?(time)
      "warning"
    else
      "success"
    end
  end

  def display_arrival_time(time)
    return "Not Available" if time.nil? 
    return "Arriving" if time <= 0
    return "1 minute" if time == 1
    "#{time} minutes"
  end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/buses/show.html.haml
.row
  %h1= @bus.number
  %ul
    - @bus_routes.each do |station|
      %li= "#{station.try(:description)} (#{station.try(:code)})"

app/views/layouts/application.html.haml
!!!
%html
  %head
    = javascript_include_tag "vendor/modernizr"
    = #javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SgBusLol
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
  %body
    = render "shared/navbar"
    = yield
    = javascript_include_tag 'application'

app/views/shared/_navbar.html.haml
.fixed
  %nav.top-bar{"data-topbar" => true, "data-no-turbolink" => true, :role => "navigation"}
    %ul.title-area
      %li.name
        %h1
          = link_to "SG Bus LoL", root_path
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      %ul.left
        %li
          = link_to "Nearby buses", site_location_path
        %li
          = form_tag site_search_path, method: :get do
            .row.collapse
              .small-8.columns
                = text_field_tag :search, nil, placeholder: "Search bus or station"
              .small-4.columns
                = submit_tag "Search", class: "alert button expand"

app/views/site/index.html.haml
#template
  .row
    %ul.accordion{ "data-accordion" => true }
      - @stations.each.with_index do |station, index|
        - station = StationDecorator.new(station)
        %li.accordion-navigation{ id: "station-#{station.code}" }
          = link_to "#{station.description} (#{station.code})", "#panel#{station.code}", class: "text-center station", "data-panel" => "#{station.code}"
          .panel-container{ id: "#{station.code}", hidden: true}
            .row
              .small-4.columns.text-center
                %p.bold Bus Number
              .small-4.columns
                %p.bold.text-center Arrival Time
              .small-4.columns
                %p.bold.text-center Next Bus
            - station.all_buses.each do |bus|
              %div{ class: "content", id: "panel#{station.code}" }
                .row
                  .small-4.columns.text-center
                    = link_to bus["code"], bus_path(bus["code"], station_code: station.code), class: "round #{color_code(bus["arrival_time"])} button"
                  .small-4.columns
                    %p.text-center= display_arrival_time(bus["arrival_time"])
                  .small-4.columns
                    %p.text-center= display_arrival_time(bus["next_bus_arrival_time"])
            .row
              .text-center
                = link_to "#/", class: "reload-station", "data-station" => "#{station.code}" do
                  %i.fi-loop

    = paginate @stations

app/views/site/location.html.haml
#location.row
  .location
    %h1.text-center Nearby buses at your location

  #template
    = image_tag  "spinnerBig.gif", class: "spinner"

app/views/stations/show.html.haml
#template
  .row
    %ul.accordion{ "data-accordion" => true }
      %li.accordion-navigation
        = link_to "#{@station.description} (#{@station.code})", "#panel#{@station.code}", class: "text-center station", "data-panel" => "#{@station.code}"
        .panel-container{ id: "#{@station.code}", hidden: true}
          .row
            .small-4.columns
              %p.bold Bus Number
            .small-4.columns
              %p.bold.text-center Arrival Time
            .small-4.columns
              %p.bold.text-center Next Bus Arrival Time
          - @station.all_buses.each do |bus|
            %div{ class: "content", id: "panel#{@station.code}" }
              .row
                .small-4.columns
                  = link_to bus["code"], bus_path(bus["code"], station_code: @station.code), class: "round #{color_code(bus["arrival_time"])} button"
                .small-4.columns
                  %p.text-center= display_arrival_time(bus["arrival_time"])
                .small-4.columns
                  %p.text-center= display_arrival_time(bus["next_bus_arrival_time"])